[project]
authors = ["Sina <s.j.semnani@gmail.com>"]
channels = ["pytorch", "conda-forge", "main", "r", "msys2"]
description = "Add a short description here"
name = "wikichat"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "3.11.*"
pytorch = "*"
pip = "*"
cchardet = "*"
lxml = "*"
gcc = "*"
gxx = "*"
make = "*"

[pypi-dependencies]
invoke = "*"
docker = "*"
transformers = ">=4.38"
datasets = "*"
evaluate = "*"
scipy = "*"
spacy = "*"
pytest = "*"
pytest-asyncio = "*"
pytest-order = "*"
langcodes = "*"
chainlite = "==0.4.4"
loguru = "*"
fastapi = "*"
streaming-form-data = "*"
email-validator = "*"
slowapi = { git = "https://github.com/laurentS/slowapi.git", rev = "a72bcc66597f620f04bf5be3676e40ed308d3a6a" }
async-lru = "*"
gunicorn = "*"
uvicorn = { version = "*", extras = ["standard"] }
qdrant-client = "==1.13"
onnxruntime = "*"
psutil = "*"
chainlit = "==1.3"
pymongo = "*"
matplotlib = "*"
json-repair = "*"
markdown = "*"
beautifulsoup4 = "*"
orjsonl = "*"
ruff = ">=0.11.4, <0.12"
docling = ">=2.28.4, <3"
diskcache = ">=5.6.3, <6"
